name: Pub.dev Publish

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken":"${{ secrets.ACCESSTOKEN }}",
          "refreshToken":"${{ secrets.REFRESHTOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": 1612792332380
        }
        EOF
    - name: Publish package
      run: pub publish -f
